name: three
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  go_router:
  flutter_hooks:
  hooks_riverpod:
  riverpod_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  riverpod_generator:
flutter:
  uses-material-design: true

scripts: derry.yaml
